version: "3.7"
services:
  app2:
    image: zayuh/coin:lasted
    user: "1003:983"
    ports:
      - "12000:12000"
    cap_add:
      - NET_ADMIN
    restart: always
    build: .
    links:
      - mongodb2
    volumes:
      - "~/data/profile:/src/coin/resource/profile"
      - "~/data/image:/src/coin/resource/image"

  mongodb2:
    image: mongo:4.4.4
    user: "1003:983"
    environment:
      MONGO_INITDB_ROOT_USERNAME: coin
      MONGO_INITDB_ROOT_PASSWORD: Duan2.22ti!
    command: ["--bind_ip", "0.0.0.0"]
    ports:
      - "12001:27017"
    volumes:
      - "~/data/mongodb:/data/db"
    restart: always
